-- Apartado A
-- Usando los ficheros hospital_tables.sql y hospital_data.sql disponibles en Moodle,
-- crear la base de datos hospital management system y cargar todos los datos disponibles
-- que van a ser objeto de procesos en puntos posteriores.
